# Generated by Django 5.2.3 on 2025-06-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
