# Generated by Django 5.2.3 on 2025-07-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_doctormessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormessage',
            name='document_url',
        ),
        migrations.AddField(
            model_name='doctormessage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
